topics:
  -
    topic: "/${ROBOT_NAME}/imu/RPY"  # Topic name using the variable
    type: geometry_msgs/msg/Vector3
    queue_size: 1
  -
    topic: "${ROBOT_NAME}/speech2text"
    type: std_msgs/msg/String
    queue_size: 1
  -
    topic: "/${ROBOT_NAME}/cmd_vel"
    type: geometry_msgs/msg/Twist
    queue_size: 1
  -
    topic: "/${ROBOT_NAME}/alterego_state/lowerbody"  # Custom_msg
    type: alterego_msgs/msg/LowerBodyState
    queue_size: 1
  -
    topic: "/${ROBOT_NAME}/odom"
    type: nav_msgs/msg/Odometry
    queue_size: 1
  -
    topic: "/${ROBOT_NAME}/scan"
    type: sensor_msgs/msg/LaserScan
    queue_size: 1

services_2_to_1: []

services_1_to_2: []
